Vagrant.configure("2") do |config|
  (1..4).each do |i|
    config.vm.define "k8s-node-#{i}" do |node|
      node.vm.box = "generic/alpine38"
      node.vm.hostname = "k8s-node-#{i}"
      node.vm.network "private_network", ip: "192.168.1.#{i + 99}"
      node.vm.synced_folder "../data", "/vagrant_data"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-node-#{i}"
        vb.gui = false
        vb.cpus = 4
        vb.memory = "2048"
      end

      node.vm.provision "shell", inline: <<-SHELL
      sudo cp /etc/apk/repositories /etc/apk/repositories.bp
      sudo sed -i 's#https\?://mirrors.edge.kernel.org/alpine#https://mirror.nju.edu.cn/alpine#g' /etc/apk/repositories
      sudo apk update
      sudo apk add docker
      SHELL

    end
  end
end
